### ISSUE TITLE
Matter with Building on IOS

### ISSUE THREAD

**Issue by royalcheese71** [navisens/NaviDocs#6]
Hello !

I was trying to do your simple app Beer for IOS, but it seems not to build :
`Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler:`

the SDK does not appear in the TARGETS of pod project in order to force the SWIFT version. 
Is this normal ?

Thanks a lot !

**Comment by emerciercontexeo** [comment]
Hi, sorry for the late answer.

I will invistigate as soon as possible.

**Comment by jamesgrantham** [comment]
Hi Roy, sorry for the delay here. The modules should be compiled for 4.2 as of December.
