### ISSUE TITLE
Resetting Accelerometer and Gyroscope reading

### ISSUE THREAD

**Issue by Wyzrk** [navisens/NaviDocs#7]
Hi, I wanted to know a few things. I am using the Android SDK to develop an application but I stumble upon some questions.
1. Is it possible to reset accelerometer and gyroscope reading without shutting down the entire SDK?
2. Will this method reset any accumulated error on accelerometer and gyroscope? 
`void setLocationLatitudeLongitude(double lat, double lng)`

**Comment by adonikian** [comment]
Hi,

1) You can pause and resume our SDK with the pause and resume methods. Please see:

- https://github.com/navisens/NaviDocs/blob/master/API.iOS.md#pause
- https://github.com/navisens/NaviDocs/blob/master/API.Android.md#void-pause

This does not "reset" readings, it simply pauses and resumes our SDK.

2) We provide methods for you to override and set the current position at any time. You can use this to reset any error in position and to set an initial position. You can do this either in global (lat, lon) coordinates or Cartesian (x, y) coordinates with the following methods:
- `void setLocationLatitudeLongitude(double lat, double lng)`
- `void setCartesianPositionXY(double x, double y)`
